### ISSUE TITLE
[Suggestion] Compatilility with Dye Depot

### ISSUE THREAD

**Issue by medsal15** [MehVahdJukaar/labels-multi#42]
[Dye Depot](https://modrinth.com/mod/dye-depot) adds 16 new dyes, but when any is applied to a label, the label will just render a grayscale version of the item.

**Comment by MehVahdJukaar** [comment]
i think my system supports it but since labels use custom colors one would need to manually edit the texture that they use (theres a palette strip) to include new ones

**Comment by MehVahdJukaar** [comment]
should be done by that mod or by users, not by me as the colors there and their order will change depending on installedmods that add more

**Comment by MehVahdJukaar** [comment]
also is this an issue in latest version? by default they should default to a dye color tint color if no texture is provided

**Comment by taker99** [comment]
> also is this an issue in latest version? by default they should default to a dye color tint color if no texture is provided

I have both your mod and the Dye Depot installed. If I apply a modded dye, it doesn't change the color. As you mentioned, I need to create a color palette to support this through a resource pack. How can I do that? Sadly, I don't have much experience with creating packs.

**Comment by kettle4boilin** [comment]
> also is this an issue in latest version? by default they should default to a dye color tint color if no texture is provided

I'm using the 1.20.1 version so I'm not sure how much has changed since, but I made a resource pack which adds the correct texture colors and it doesn't work. I'm not super familiar with Minecraft's code, but my guess would be the vanilla 'DyeColor' class clamps at index 15?

Not sure if there's a way for you to allow the value to be greater that that, though it would be great if you could!

**Comment by AStrangeMouse** [comment]
Can confirm on **1.20.1** that adding additional colors to the palette strip texture does not seem to work. Here's an example error from my log (in a lightly-modded setup), if that helps any:

```
[22:45:05] [Render thread/WARN] [Labels/]: Failed to correctly create label image for NativeImage[RGBA 16x16@2996736820224N]:
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?] {}
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?] {}
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?] {}
	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?] {re:mixin}
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?] {re:mixin}
	at net.mehvahdjukaar.labels.LabelEntityRenderer.lambda$fastInPlaceRecolor$5(LabelEntityRenderer.java:271) ~[labels-1.20-2.0.0.jar%23366!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.resources.textures.SpriteUtils.forEachPixel(SpriteUtils.java:36) ~[moonlight-1.20-2.16.27-forge.jar%23377!/:?] {re:classloading}
	at net.mehvahdjukaar.labels.LabelEntityRenderer.fastInPlaceRecolor(LabelEntityRenderer.java:265) ~[labels-1.20-2.0.0.jar%23366!/:?] {re:classloading}
	at net.mehvahdjukaar.labels.LabelEntityRenderer.postProcess(LabelEntityRenderer.java:250) ~[labels-1.20-2.0.0.jar%23366!/:?] {re:classloading}
	at net.mehvahdjukaar.labels.LabelEntityRenderer.lambda$render$0(LabelEntityRenderer.java:102) ~[labels-1.20-2.0.0.jar%23366!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.client.texture_renderer.RenderedTexturesManager.lambda$requestFlatItemTexture$2(RenderedTexturesManager.java:110) ~[moonlight-1.20-2.16.27-forge.jar%23377!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.client.texture_renderer.FrameBufferBackedDynamicTexture.redraw(FrameBufferBackedDynamicTexture.java:80) ~[moonlight-1.20-2.16.27-forge.jar%23377!/:?] {re:classloading}
	at net.mehvahdjukaar.moonlight.api.client.texture_renderer.FrameBufferBackedDynamicTexture.initialize(FrameBufferBackedDynamicTexture.java:63) ~[moonlight-1.20-2.16.27-forge.jar%23377!/:?] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:226) ~[client-1.20.1-20230612.114412-srg.jar%23430!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:workarounds.event_loop.RenderSystemMixin from mod embeddium,pl:mixin:A}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213) ~[client-1.20.1-20230612.114412-srg.jar%23430!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:workarounds.event_loop.RenderSystemMixin from mod embeddium,pl:mixin:A}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23430!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinWindow from mod immediatelyfast,pl:mixin:APP:embeddium.mixins.json:workarounds.context_creation.WindowMixin from mod embeddium,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23430!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23430!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.4.16.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.4.16.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.4.16.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:115) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}
```
